<?php

namespace App\Enums;

enum MunicipalityEnum: string
{
    public static function getByDepartment(DepartmentEnum $department): array
    {
        $municipalities = match ($department) {
            DepartmentEnum::ATLANTIDA => [
                'La Ceiba' => 'La Ceiba',
                'El Porvenir' => 'El Porvenir',
                'Tela' => 'Tela',
                'Jutiapa' => 'Jutiapa',
                'La Masica' => 'La Masica',
                'San Francisco' => 'San Francisco',
                'Arizona' => 'Arizona',
                'Esparta' => 'Esparta',
            ],
            DepartmentEnum::CHOLUTECA => [
                'Choluteca' => 'Choluteca',
                'Apacilagua' => 'Apacilagua',
                'Concepción de María' => 'Concepción de María',
                'Duyure' => 'Duyure',
                'El Corpus' => 'El Corpus',
                'El Triunfo' => 'El Triunfo',
                'Marcovia' => 'Marcovia',
                'Morolica' => 'Morolica',
                'Namasigüe' => 'Namasigüe',
                'Orocuina' => 'Orocuina',
                'Pespire' => 'Pespire',
                'San Antonio de Flores' => 'San Antonio de Flores',
                'San Isidro' => 'San Isidro',
                'San José' => 'San José',
                'San Marcos de Colón' => 'San Marcos de Colón',
                'Santa Ana de Yusguare' => 'Santa Ana de Yusguare',
            ],
            DepartmentEnum::COLON => [
                'Trujillo' => 'Trujillo',
                'Balfate' => 'Balfate',
                'Iriona' => 'Iriona',
                'Limón' => 'Limón',
                'Sabá' => 'Sabá',
                'Santa Fe' => 'Santa Fe',
                'Santa Rosa de Aguán' => 'Santa Rosa de Aguán',
                'Sonaguera' => 'Sonaguera',
                'Tocoa' => 'Tocoa',
                'Bonito Oriental' => 'Bonito Oriental',
            ],
            DepartmentEnum::COMAYAGUA => [
                'Comayagua' => 'Comayagua',
                'Ajuterique' => 'Ajuterique',
                'El Rosario' => 'El Rosario',
                'Esquías' => 'Esquías',
                'Humuya' => 'Humuya',
                'La Libertad' => 'La Libertad',
                'Lamaní' => 'Lamaní',
                'La Trinidad' => 'La Trinidad',
                'Lejamaní' => 'Lejamaní',
                'Meámbar' => 'Meámbar',
                'Minas de Oro' => 'Minas de Oro',
                'Ojos de Agua' => 'Ojos de Agua',
                'San Jerónimo' => 'San Jerónimo',
                'San José de Comayagua' => 'San José de Comayagua',
                'San José del Potrero' => 'San José del Potrero',
                'San Luis' => 'San Luis',
                'San Sebastián' => 'San Sebastián',
                'Siguatepeque' => 'Siguatepeque',
                'Villa de San Antonio' => 'Villa de San Antonio',
                'Las Lajas' => 'Las Lajas',
                'Taulabé' => 'Taulabé',
            ],
            DepartmentEnum::COPAN => [
                'Santa Rosa de Copán' => 'Santa Rosa de Copán',
                'Cabañas' => 'Cabañas',
                'Concepción' => 'Concepción',
                'Copán Ruinas' => 'Copán Ruinas',
                'Corquín' => 'Corquín',
                'Cucuyagua' => 'Cucuyagua',
                'Dolores' => 'Dolores',
                'Dulce Nombre' => 'Dulce Nombre',
                'El Paraíso' => 'El Paraíso',
                'Florida' => 'Florida',
                'La Jigua' => 'La Jigua',
                'La Unión' => 'La Unión',
                'Nueva Arcadia' => 'Nueva Arcadia',
                'San Agustín' => 'San Agustín',
                'San Antonio' => 'San Antonio',
                'San Jerónimo' => 'San Jerónimo',
                'San José' => 'San José',
                'San Juan de Opoa' => 'San Juan de Opoa',
                'San Nicolás' => 'San Nicolás',
                'San Pedro' => 'San Pedro',
                'Santa Rita' => 'Santa Rita',
                'Trinidad' => 'Trinidad',
                'Veracruz' => 'Veracruz',
            ],
            DepartmentEnum::CORTES => [
                'San Pedro Sula' => 'San Pedro Sula',
                'Choloma' => 'Choloma',
                'Omoa' => 'Omoa',
                'Pimienta' => 'Pimienta',
                'Potrerillos' => 'Potrerillos',
                'Puerto Cortés' => 'Puerto Cortés',
                'San Antonio de Cortés' => 'San Antonio de Cortés',
                'San Francisco de Yojoa' => 'San Francisco de Yojoa',
                'San Manuel' => 'San Manuel',
                'Santa Cruz de Yojoa' => 'Santa Cruz de Yojoa',
                'Villanueva' => 'Villanueva',
                'La Lima' => 'La Lima',
            ],
            // Continuar con la misma estructura para los demás departamentos
            DepartmentEnum::EL_PARAISO => [
                'Yuscarán' => 'Yuscarán',
                'Alauca' => 'Alauca',
                'Danlí' => 'Danlí',
                'El Paraíso' => 'El Paraíso',
                'Güinope' => 'Güinope',
                'Jacaleapa' => 'Jacaleapa',
                'Liure' => 'Liure',
                'Morocelí' => 'Morocelí',
                'Oropolí' => 'Oropolí',
                'Potrerillos' => 'Potrerillos',
                'San Antonio de Flores' => 'San Antonio de Flores',
                'San Lucas' => 'San Lucas',
                'San Matías' => 'San Matías',
                'Soledad' => 'Soledad',
                'Teupasenti' => 'Teupasenti',
                'Texiguat' => 'Texiguat',
                'Vado Ancho' => 'Vado Ancho',
                'Yauyupe' => 'Yauyupe',
                'Trojes' => 'Trojes',
            ],
            // Y así sucesivamente para el resto de departamentos...
            default => [],
        };

        return $municipalities;
    }
}
